# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: led.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'led.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tled.proto\"^\n\nLedCommand\x12(\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x17.LedCommand.CommandType\"&\n\x0b\x43ommandType\x12\x0b\n\x07LED_OFF\x10\x00\x12\n\n\x06LED_ON\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'led_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEDCOMMAND']._serialized_start=13
  _globals['_LEDCOMMAND']._serialized_end=107
  _globals['_LEDCOMMAND_COMMANDTYPE']._serialized_start=69
  _globals['_LEDCOMMAND_COMMANDTYPE']._serialized_end=107
# @@protoc_insertion_point(module_scope)
